title = "2030ST"
description = "Scenario based on TYNDP2018 ST 2030"
name = "2030ST"

[scenario]
investment = ["storage"]
DE_system = "" # german data (generation, load, etc.)
DE_heat_system = "2030GL"
EU_load = "2030ST" # european load
EU_generation = "2030 ST" # european generation mix based on TYNDP
cost = "2030ST" # carrier cost (gas, co2, etc.)
grid = "2030"
year = 2030
weather_year = 2011 # 2011, 2012
grid_loss = 0.03
pv_profiles = "ninja"
onshore_profiles = "ninja"
offshore_profiles = "eGo"
decentral_heat-flex-share = 1

[sensitivities.electricity]
DE-electricity-load = 571e3

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "NL",
    "LU",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NL",
  "LU",
  "NO",
  "PL",
  "SE"
]

[buses.heat]
#central = ["DE"]
decentral = ["DE"]
flex-decentral = ["DE"]
