title = "NEP 2030A Scenario"
description = "Based on NEP2019 Scenario 2030A. The scenario has lower renewable capacities and lower demands than the 2030C scenario."
name = "2030A"

parents = ["scenarios/2030C.toml"]

[scenario]
DE_system = "A2030" # german data (generation, load, etc.)
EU_load = "2030EU" # european load
EU_generation = "2030 EUCO" # european generation mix based on TYNDP
