title = "2040DG"
description = "Scenario for ANGUS project, year 2040 (based on TYNDP2018 2040 GCA)"
name = "2040DG"

[scenario]
DE_system = "" # german data (generation, load, etc.)
DE_heat_system = "2040GL"
EU_load = "2040DG" # european load
EU_generation = "2040 DG" # european generation mix based on TYNDP
cost = "2040DG" # carrier cost (gas, co2, etc.)
grid = "2040DG"
weather_year = 2011
year = 2040
grid_loss = 0.03
pv_profiles = "ninja"
onshore_profiles = "ninja"
offshore_profiles = "eGo"
decentral_heat-flex-share =  1

[sensitivities.electricity]
DE-electricity-load = 601e3

[buses]
electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "NL",
    "LU",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NL",
  "LU",
  "NO",
  "PL",
  "SE"
]

[buses.heat]
#central = ["DE"]
decentral = ["DE"]
flex-decentral = ["DE"]
