title = "2050ZNES-thflex"
description = "Scenario for ANGUS project, year 2050 (based on Ehighway 100 % RES). With flexible heat pump."
name = "2050ZNES-thflex"

parents = ["scenarios/2050ZNES.toml"]

[sensitivities]
DE-electricity-load = 571e3

[buses.heat]
#central = ["DE"]
decentral = ["DE"]
