title = "2050ZNES"
description = "Scenario for ANGUS project, year 2050 (based on Ehighway 100 % RES)."
name = "2050ZNES"


[scenario]
DE_system = "2050ZNES"
EU_load = "100% RES" # european load
EU_generation = "100% RES" # european generation mix based on
cost = "2050ZNES" # carrier cost (gas, co2, etc.)
grid = "100% RES"
year = 2050
weather_year = 2011
grid_loss = 0.03
pv_profiles = "ninja"
onshore_profiles = "ninja"
offshore_profiles = "eGo"


[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "NL",
    "LU",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NL",
  "LU",
  "NO",
  "PL",
  "SE"
]
