title = "ANGUS2030-DG"
description = "Scenario for ANGUS project, year 2030 (based on TYNDP2018 DG)"
name = "ANGUS2030-DG"

parents = ["scenarios/ANGUS2030-ST.toml"]


[scenario]
DE_system = "" # german data (generation, load, etc.)
EU_load = "2030DG" # european load
EU_generation = "2030 DG" # european generation mix based on TYNDP
cost = "2030DG" # carrier cost (gas, co2, etc.)
grid = "2030"
