title = "ANGUS2040-ST"
description = "Scenario for ANGUS project, year 2040 (based on TYNDP2018, ST)."
name = "ANGUS2040-ST"

parents = ["scenarios/ANGUS2030-ST.toml"]

[scenario]
DE_system = ""
EU_load = "2040ST" # european load
EU_generation = "2040 ST" # european generation mix based on TYNDP
cost = "2040ST" # carrier cost (gas, co2, etc.)
grid = "2040ST"
year = 2040
