title = "ANGUS2040-DG"
description = "Scenario for ANGUS project, year 2040 (based on TYNDP2018, DG)."
name = "ANGUS2040-DG"

parents = ["scenarios/ANGUS2030-ST.toml"]

[scenario]
DE_system = ""
EU_load = "2040DG" # european load
EU_generation = "2040 DG" # european generation mix based on TYNDP
cost = "2040DG" # carrier cost (gas, co2, etc.)
grid = "2040DG"
year = 2040
