title = "ANGUS2030-ST"
description = "Scenario for ANGUS project, year 2030 (based on TYNDP2018 ST)"
name = "ANGUS2030-ST"

[scenario]
DE_system = "" # german data (generation, load, etc.)
EU_load = "2030ST" # european load
EU_generation = "2030 ST" # european generation mix based on TYNDP
cost = "2030ST" # carrier cost (gas, co2, etc.)
grid = "2030"
year = 2030
weather_year = 2012 # 2011, 2012
grid_loss = 0.05
renewable_profiles = "ninja" # emhires

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "LU",
    "NL",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NL",
  "LU",
  "NO",
  "PL",
  "SE"
]
