title = "ANGUS2050"
description = "Scenario for ANGUS project, year 2050 (based on Ehighway 100 % RES)."
name = "ANGUS2050"

parents = ["scenarios/ANGUS2030.toml"]

[scenario]
DE_system = "ANGUS2050"
EU_load = "100% RES" # european load
EU_generation = "100% RES" # european generation mix based on
cost = "2050-100RE" # carrier cost (gas, co2, etc.)
grid = "100% RES"
year = 2050
