title = ""
description = ""
name = "eHighway2050-100%RES"

[scenario]
EU_load = "100% RES" # european load
EU_generation = "100% RES" # european generation mix based on TYNDP
cost = "2030ST" # carrier cost (gas, co2, etc.)
grid = "100% RES"
year = 2050
weather_year = 2012 # 2011, 2012
demand_year = 2012 # 2011, 2012
grid_loss = 0.05

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "IT",
    "NL",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "IT",
  "NL",
  "NO",
  "PL",
  "SE"
]
