title = ""
description = ""
name = "NEP2030-C"

[scenario]
nep = "C2030" # german data (generation, load, etc.)
cost = "2030ST" # carrier cost (gas, co2, etc.)
load = "2030ST" # european load
generation = "vision4" # european generation mix based on TYNDP
grid = ""
year = 2030 


[grid]
loss = 0.05

[temporal]
weather_year = 2012 # 2011, 2012
demand_year = 2012 # 2011, 2012

[potential]
renewables = "LIMES-EU"
biomass = "hotmaps"

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "IT",
    "NL",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "IT",
  "NL",
  "NO",
  "PL",
  "SE"
]
