title = ""
description = ""
name = "NEP2030-C"
nep_scenario = "C2030"


[cost]
wacc = 0.07

[tyndp]
load = "2030ST"
generation = 'vision4'
cost = "2030ST"

[grid]
loss = 0.05

[availability_factor]
biomass = 0.85
coal =  0.85
gas = 0.85
uranium =  0.85
oil =  0.85
lignite =  0.85

[efficiencies]
biomass = 0.35
coal =  0.45
gas = 0.5
uranium = 0.35
oil = 0.35
lignite = 0.38
battery = 0.9

[max_fulloadhours]
other_non_renewables = 4000

[temporal]
scenario_year = 2030
weather_year = 2012 # 2011, 2012
demand_year = 2012 # 2011, 2012

[potential]
renewables = "LIMES-EU"
biomass = "hotmaps"

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "NL",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NL",
  "NO",
  "PL",
  "SE"
]
