title = ""
description = ""
name = "NEP2030-C"

[cost]
wacc = 0.07

[tyndp]
load = "2030ST"
generation = 'vision4' # vision1, vision2, vision3, vision4

[grid]
loss = 0.05

[availability_factor]
biomass = 0.85
coal =  0.85
gas = 0.85
uranium =  0.85
oil =  0.85
lignite =  0.85

[temporal]
scenario_year = 2030
weather_year = 2012 # 2011, 2012
demand_year = 2012 # 2011, 2012

[potential]
renewables = "LIMES-EU"
biomass = "hotmaps"

[buses]

electricity = [
    "AT",
    "BE",
    "CH",
    "CZ",
    "DE",
    "DK",
    "FR",
    "NO",
    "PL",
    "SE"
]

biomass = [
  "AT",
  "BE",
  "CH",
  "CZ",
  "DE",
  "DK",
  "FR",
  "NO",
  "PL",
  "SE"
]
